language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -r requirements_dev.txt
  - pip install coverage flake8 nose mock pep8-naming
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-branches --cover-package honcho test/unit
  - nosetests test/integration
  - flake8 honcho test
after_success:
  - coveralls
